let listaCompras = [
    {"id": 1, "Nome": "Arroz", "Quantidade": 10, "Valor Unitário": 5.99},
    {"id": 2, "Nome": "Feijão", "Quantidade": 20, "Valor Unitário": 7.99},
    {"id": 3, "Nome": "Açúcar", "Quantidade": 15, "Valor Unitário": 4.99},
    {"id": 4, "Nome": "Sal", "Quantidade": 25, "Valor Unitário": 2.99},
    {"id": 5, "Nome": "Macarrão", "Quantidade": 30, "Valor Unitário": 3.99},
    {"id": 6, "Nome": "Óleo de Soja", "Quantidade": 12, "Valor Unitário": 8.99},
    {"id": 7, "Nome": "Café", "Quantidade": 17, "Valor Unitário": 14.99},
    {"id": 8, "Nome": "Leite", "Quantidade": 22, "Valor Unitário": 3.49},
    {"id": 9, "Nome": "Pão", "Quantidade": 50, "Valor Unitário": 0.99},
    {"id": 10, "Nome": "Manteiga", "Quantidade": 18, "Valor Unitário": 6.49},
    {"id": 11, "Nome": "Queijo", "Quantidade": 10, "Valor Unitário": 12.99},
    {"id": 12, "Nome": "Presunto", "Quantidade": 15, "Valor Unitário": 11.99},
    {"id": 13, "Nome": "Iogurte", "Quantidade": 20, "Valor Unitário": 5.49},
    {"id": 14, "Nome": "Chocolate", "Quantidade": 25, "Valor Unitário": 3.99},
    {"id": 15, "Nome": "Biscoito", "Quantidade": 30, "Valor Unitário": 2.99},
    {"id": 16, "Nome": "Frango", "Quantidade": 10, "Valor Unitário": 9.99},
    {"id": 17, "Nome": "Carne Bovina", "Quantidade": 5, "Valor Unitário": 22.99},
    {"id": 18, "Nome": "Peixe", "Quantidade": 8, "Valor Unitário": 17.99},
    {"id": 19, "Nome": "Camarão", "Quantidade": 4, "Valor Unitário": 35.99},
    {"id": 20, "Nome": "Salsicha", "Quantidade": 20, "Valor Unitário": 4.99},
    {"id": 21, "Nome": "Sabão em Pó", "Quantidade": 15, "Valor Unitário": 10.99},
    {"id": 22, "Nome": "Amaciante", "Quantidade": 12, "Valor Unitário": 7.99},
    {"id": 23, "Nome": "Detergente", "Quantidade": 20, "Valor Unitário": 1.99},
    {"id": 24, "Nome": "Esponja de Lavar", "Quantidade": 30, "Valor Unitário": 0.50},
    {"id": 25, "Nome": "Papel Higiênico", "Quantidade": 50, "Valor Unitário": 0.99},
    {"id": 26, "Nome": "Shampoo", "Quantidade": 15, "Valor Unitário": 9.99},
    {"id": 27, "Nome": "Condicionador", "Quantidade": 15, "Valor Unitário": 9.99},
    {"id": 28, "Nome": "Desodorante", "Quantidade": 20, "Valor Unitário": 8.99},
    {"id": 29, "Nome": "Creme Dental", "Quantidade": 25, "Valor Unitário": 4.99},
    {"id": 30, "Nome": "Escova de Dente", "Quantidade": 30, "Valor Unitário": 3.99},
];